pipeline:
  build:
    privileged: true
    image: quay.io/ukhomeofficedigital/openjdk8:v1.1.0
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - echo "nothing to do!"
    when:
     event: [push, pull_request, tag]

  docker-build:
    privileged: true
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t hocs-ui .
    when:
      branch: [master, refs/tags/*]
      event: [push, tag]

  push:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+hocs_ui" -p=${DOCKER_PASSWORD} quay.io
      - docker tag hocs-ui quay.io/ukhomeofficedigital/hocs-ui
      - docker tag hocs-ui quay.io/ukhomeofficedigital/hocs-ui:build-${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/hocs-ui:latest
      - docker push quay.io/ukhomeofficedigital/hocs-ui:build-${DRONE_BUILD_NUMBER}
    when:
      branch: master
      event: push

  tag-docker-image-with-git-tag:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+hocs_ui" -p=${DOCKER_PASSWORD} quay.io
      - docker tag hocs-ui quay.io/ukhomeofficedigital/hocs-ui:${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/hocs-ui:${DRONE_TAG}
    when:
      event: tag

  get-kube-configuration-deployment:
     image: plugins/git
     environment:
       - DOCKER_HOST=tcp://127.0.0.1:2375
     commands:
       - git clone https://github.com/UKHomeOffice/kube-hocs-ui.git
     when:
       event: [push, deployment, tag]

  deploy-to-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v0.2.3
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - KUBE_NAMESPACE=hocs-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-dev.dsp.notprod.homeoffice.gov.uk
    commands:
      - cd kube-hocs-ui
      - ./deploy.sh
    when:
      branch: [master]
      event: [push, tag]

  deploy-to-qa-from-build-tag:
    image: quay.io/ukhomeofficedigital/kd:v0.2.3
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - KUBE_NAMESPACE=hocs-qa
      - ENVIRONMENT=qa
      - VERSION=${DRONE_TAG}
      - KUBE_SERVER=https://kube-dev.dsp.notprod.homeoffice.gov.uk
    commands:
      - cd kube-hocs-ui
      - ./deploy.sh
    when:
      event: [tag]

  deploy:
    image: quay.io/ukhomeofficedigital/kd:v0.2.3
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - KUBE_NAMESPACE=hocs-${DRONE_DEPLOY_TO}
      - ENVIRONMENT=${DRONE_DEPLOY_TO}
      - VERSION=${IMAGE_VERSION}
      - KUBE_SERVER=https://kube-dev.dsp.notprod.homeoffice.gov.uk
    commands:
      - cd kube-hocs-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: [dev, test, qa]

  deploy-to-prod:
    image: quay.io/ukhomeofficedigital/kd:v0.2.3
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - KUBE_NAMESPACE=hocs
      - ENVIRONMENT=prod
      - VERSION=${IMAGE_VERSION}
      - KUBE_SERVER=https://kube.dsp.digital.homeoffice.gov.uk
    commands:
      - cd kube-hocs-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: prod

services:
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "overlay"