version: '3.1'

services:

  clamd:
    image: mkodockx/docker-clamav
    ports:
      - "3310:3310/tcp"
    networks:
      - hocs-network

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - hocs-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hocs-network

  mysql:
   image: mysql
   ports:
     - 3306:3306
   networks:
     - hocs-network
   environment:
     MYSQL_ROOT_PASSWORD: alfresco
     MYSQL_DATABASE: alfresco
     MYSQL_USER: alfresco
     MYSQL_PASSWORD: alfresco
   restart: always
   tmpfs:
     - /var/lib/mysql

  postgres1:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - hocs-network
    environment:
     POSTGRES_USER: root
     POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

  postgres2:
    image: postgres
    ports:
      - 5433:5432
    networks:
      - hocs-network
    environment:
     POSTGRES_USER: root
     POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

  s3creator:
    image: garland/aws-cli-docker
    networks:
      - hocs-network
    entrypoint: "aws --endpoint-url http://localstack:80 s3 mb s3://UNSET"
    environment:
      AWS_ACCESS_KEY_ID: UNSET
      AWS_SECRET_ACCESS_KEY: UNSET
      AWS_DEFAULT_REGION: eu-west-1
    depends_on:
     - localstack

  localstack:
    image: localstack/localstack:latest
    ports:
      - 4572:80
      - 9080:8080
    networks:
      - hocs-network
    environment:
      HOSTNAME_EXTERNAL: localstack
      SERVICES: s3:80
      DEFAULT_REGION: eu-west-1

  alfresco:
    build:
      context: ../hocs-alfresco
    #image: quay.io/ukhomeofficedigital/hocs-alfresco
    environment:
      ALF_S3_ACCESSKEY: UNSET
      ALF_S3_SECRETKEY: UNSET
      ALF_S3_BUCKETNAME: UNSET
      ALF_S3_HOSTNAME: localstack
      ALF_DB_USERNAME: alfresco
      ALF_DB_PASSWORD: alfresco
      ALF_DB_NAME: alfresco
      ALF_DB_HOST: mysql
      ALF_DB_PORT: 3306
      ALF_ADMIN_INITIAL_PASSWORD: 209c6174da490caeb422f3fa5a7ae634
      ALF_REPORTING_ENDPOINT: rabbitmq
    depends_on:
      - s3creator
      - mysql
    ports:
      - 8083:8080
    networks:
      - hocs-network
    tmpfs:
      /usr/local/alfresco/alf_data

  reporting:
    build:
      context: ../hocs-reporting-service
    #image: quay.io/ukhomeofficedigital/hocs-reporting-service
    environment:
      spring.profiles.active: postgres, rabbitmq
      db.host: postgres2
      db.username: root
      db.password: dev
      db.schema.name: public
      env.rabbit.mq.host: rabbitmq
    depends_on:
      - postgres2
      - rabbitmq
    ports:
      - 8082:8080
    networks:
      - hocs-network

  data-service:
    build:
      context: ../hocs-data-service
    #image: quay.io/ukhomeofficedigital/hocs-data-service
    environment:
      spring.profiles.active: postgres
      db.host: postgres1
      db.username: root
      db.password: dev
      db.schema.name: public
      redis.host: redis
      alf.api.host: http://alfresco:8080
    depends_on:
      - postgres1
      - redis
    ports:
      - 8081:8080
    networks:
      - hocs-network
    command: /app/scripts/run.sh data-service:8080 /app/data admin admin alfresco:8080
    volumes:
      - ../hocs-data/data/:/app/data/

  ui:
    build:
      context: .
    volumes:
      - ./out/logs/nginx/:/var/log/nginx
      - ./frontend/var/:/var/www/symfony/var
    ports:
      - 8080:8080
    environment:
      SYMFONY_ENV: dc
      APP_ENV: dc
      APP_PHP: app_dev\.php
    networks:
      - hocs-network

networks:
  hocs-network: