imports:
    - { resource: config.yml }

home_office_alfresco_api:
    list_endpoint: 'https://hocs-alfresco:443/alfresco/'

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        console:
            type:  console