imports:
    - { resource: config.yml }

home_office_alfresco_api:
    list_endpoint: 'https://hocs-data-service.hocs.svc.cluster.local'
    endpoint: 'https://hocs-alfresco.hocs.svc.cluster.local/alfresco/'

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        console:
            type:  console

parameters:
    home_office_cts.routing.ssl_redirects: true