imports:
    - { resource: config.yml }

home_office_alfresco_api:
    list_endpoint: 'https://hocs-data-service.alf-dev.svc.cluster.local'
    endpoint: 'https://hocs-alfresco.alf-dev.svc.cluster.local/alfresco/'

monolog:
    handlers:
        console:
            type:   console
            bubble: true
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info


home_office_list:
    cache_timeout_seconds: 36000

parameters:
    home_office_cts.routing.ssl_redirects: true

