imports:
    - { resource: config.yml }

home_office_alfresco_api:
    list_endpoint: 'https://hocs-alfresco.hocs-dev.svc.cluster.local/alfresco/'
    endpoint: 'https://hocs-alfresco.hocs-dev.svc.cluster.local/alfresco/'

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
#    toolbar: %debug_toolbar%
    intercept_redirects: %debug_redirects%

monolog:
    handlers:
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: false

#swiftmailer:
#    delivery_address: me@example.com

home_office_list:
    cache_timeout_seconds: 60

parameters:
    home_office_cts.routing.ssl_redirects: true

