parameters:
#    home_office_process_manager_interface.example.class: HomeOffice\CtsBundle\Example

services:
#    home_office_process_manager_interface.example:
#        class: %home_office_process_manager_interface.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
